title: Место упокоения семьи Думченко
domain: dumchenko.github.io
baseurl: "/graveyard" # the subpath of your site, e.g. /blog
url: "https://dumchenko.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  # - jekyll-webp
  - jekyll-loading-lazy
  - jekyll-timeago
  - premonition
  - jekyll-seo-tag

collections_dir: collections
collections:
  people:
    output: true
  graves:
    output: true

webp:
  enabled: true
  quality: 75
  img_dir:
    - assets/images
  nested: true
  formats:
    - ".jpeg"
    - ".jpg"
    - ".png"
    - ".tiff"

  gifs:
    - ".gif"

  exclude: []

  append_ext: true

jekyll_timeago:
  depth: 2
  default_locale: ru
  available_locales:
    - en
    - ru
