name: Lint

on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Run install
        run: yarn install

      - name: Build nuxt
        run: yarn build

      - name: Run eslint
        run: yarn run lint
